# Generated by Django 4.2.2 on 2023-07-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
    ]
