# Generated by Django 4.2.2 on 2023-07-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='category',
        ),
    ]
